version: "3.4"

services:
################################################################################
# Shared infrastructure services, add/remove as needed
################################################################################
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:3.0.2
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - LOCALSTACK_HOST=127.0.0.1
      - SERVICES=s3,sqs,sns
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    healthcheck:
      test: ["CMD", "curl", "localhost:4566"]
      interval: 5s
      start_period: 4s
      retries: 3

  selenium-chrome:
    image: selenium/standalone-chrome:119.0
    container_name: selenium-chrome
    ports:
      - "4444:4444"

################################################################################
# Uncomment, configure and add your services below
################################################################################
#  your-service-name:
#    image: defradigital/your-service-name:${YOUR_SERVICE_NAME:-latest}  # Override the version by setting an environment variable YOUR_SERVICE_NAME=version.to.run
#    container_name: your-service-name
#    network_mode: "host"
#    environment:
#      - PORT=3000
#      - MONGO_URI=mongodb://mongodb:27017/?tls=false  # since we're using a bridged network, we refer to the mongo container etc by their hostname
#      - REDIS_HOST=redis
#      - LOCALSTACK_URL=http://localstack:4566
#      - AWS_REGION=eu-west-2

